[tools]
rojo = { source = "rojo-rbx/rojo", version = "7" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
selene = { source = "Kampfkarren/selene", version = "0.17.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.13.1" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
